export const sampleData = [
  {
    usernum: 1,
    icon: "/icon1.png",
    num: "k25001",
    name: "山田 太郎",
    level: 5,
    tag: [
      "初心者",
      "チョットデキル",
      "コードのひよっこ",
      "バグと戦う者",
      "Hello, World! の住人",
    ],
  },
  {
    usernum: 2,
    icon: "/icon2.png",
    num: "k25002",
    name: "佐藤 花子",
    level: 3,
    tag: [
      "中級者",
      "使い手",
      "最適化の鬼",
      "プルリク？全部見てるよ",
      "デバッグの達人",
    ],
  },
  {
    usernum: 3,
    icon: "/icon3.png",
    num: "k25003",
    name: "鈴木 一郎",
    level: 7,
    tag: [
      "上級者",
      "レガシーの征服者",
      "システムの覇者",
      "エキスパート",
      "バグと戦う者",
    ],
  },
  {
    usernum: 4,
    icon: "/icon4.png",
    num: "k25004",
    name: "高橋 健",
    level: 4,
    tag: [
      "ビギナー",
      "Hello, World! の住人",
      "中級者",
      "デバッグの達人",
      "使い手",
    ],
  },
  {
    usernum: 5,
    icon: "/icon5.png",
    num: "k25005",
    name: "田中 真美",
    level: 6,
    tag: [
      "マスター",
      "最適化の鬼",
      "レガシーの征服者",
      "初心者",
      "プルリク？全部見てるよ",
    ],
  },
  {
    usernum: 6,
    icon: "/icon6.png",
    num: "k25006",
    name: "伊藤 大輔",
    level: 8,
    tag: [
      "エキスパート",
      "使い手",
      "Hello, World! の住人",
      "バグと戦う者",
      "中級者",
    ],
  },
  {
    usernum: 7,
    icon: "/icon7.png",
    num: "k25007",
    name: "渡辺 美咲",
    level: 2,
    tag: [
      "初心者",
      "コードのひよっこ",
      "レガシーの征服者",
      "チョットデキル",
      "ビギナー",
    ],
  },
  {
    usernum: 8,
    icon: "/icon8.png",
    num: "k25008",
    name: "中村 修",
    level: 9,
    tag: [
      "システムの覇者",
      "デバッグの達人",
      "最適化の鬼",
      "エキスパート",
      "マスター",
    ],
  },
  {
    usernum: 9,
    icon: "/icon9.png",
    num: "k25009",
    name: "小林 亮",
    level: 1,
    tag: [
      "ビギナー",
      "初心者",
      "チョットデキル",
      "コードのひよっこ",
      "バグと戦う者",
    ],
  },
  {
    usernum: 10,
    icon: "/icon10.png",
    num: "k25010",
    name: "加藤 恵",
    level: 5,
    tag: [
      "プルリク？全部見てるよ",
      "レガシーの征服者",
      "Hello, World! の住人",
      "使い手",
      "システムの覇者",
    ],
  },
  {
    usernum: 11,
    icon: "/icon11.png",
    num: "k25011",
    name: "山本 蓮",
    level: 6,
    tag: [
      "エキスパート",
      "最適化の鬼",
      "デバッグの達人",
      "プルリク？全部見てるよ",
      "中級者",
    ],
  },
  {
    usernum: 12,
    icon: "/icon12.png",
    num: "k25012",
    name: "石井 直人",
    level: 7,
    tag: [
      "マスター",
      "上級者",
      "システムの覇者",
      "Hello, World! の住人",
      "初心者",
    ],
  },
  {
    usernum: 13,
    icon: "/icon13.png",
    num: "k25013",
    name: "松本 結衣",
    level: 3,
    tag: [
      "ビギナー",
      "チョットデキル",
      "使い手",
      "エキスパート",
      "レガシーの征服者",
    ],
  },
  {
    usernum: 14,
    icon: "/icon14.png",
    num: "k25014",
    name: "藤田 翼",
    level: 4,
    tag: [
      "システムの覇者",
      "デバッグの達人",
      "最適化の鬼",
      "初心者",
      "プルリク？全部見てるよ",
    ],
  },
  {
    usernum: 15,
    icon: "/icon15.png",
    num: "k25015",
    name: "岡本 直美",
    level: 8,
    tag: [
      "Hello, World! の住人",
      "レガシーの征服者",
      "エキスパート",
      "バグと戦う者",
      "マスター",
    ],
  },
];

export default sampleData;
